import { Badge, Col, Container, Row } from 'react-bootstrap';
import CountUp from 'react-countup';

const impactData = [
    {
        start: 0,
        end: 6,
        suffix: '',
        prefix: '',
        title: 'ZP Partners',
        subtitle:
            'We piloted with 6 Zilla Parishads (ZP) in Maharashtra to transform their district level education governence systems at Scale',
    },
    {
        start: 195,
        end: 200,
        suffix: 'K+',
        prefix: '',
        title: 'ZP Teachers',
        subtitle:
            'To use NIPUN Maharashtra to revolutionize how India diagnoses and addresses foundational learning gaps through AI Powered, state integrated, platforms',
    },
    {
        start: 1,
        end: 7,
        suffix: 'M+',
        prefix: '',
        title: 'Chapters Created',
        subtitle:
            'To receive personalized remedial support generated by AI to joyfully help improve their foundational learning skills',
    },
    {
        start: 1,
        end: 5.5,
        suffix: 'M+',
        prefix: '',
        title: 'Guardians',
        subtitle:
            'NIPUN Maharashtra platform will share personalized improvement plans through parent login for each child',
    },
];

const OurVision = () => {
    return (
        <section className="pt-4 pb-6 mb-4 mt-lg-4 bg-light position-relative" data-aos="fade-up">
            <div className="divider top d-none d-sm-block"></div>
            <Container>
                <Row>
                    <Col className="text-center">
                        <Badge pill bg="" className="badge-soft-success px-2 py-1">
                            stats
                        </Badge>
                        <h1 className="display-5 fw-medium">Our Impact</h1>
                    </Col>
                </Row>
                <Row className="mt-5 text-center">
                    {impactData.map((item, index) => (
                        <Col key={index} xs={6} md={3} className="mb-4 mb-sm-0">
                            <div className="display-4 fw-normal">
                                <CountUp
                                    duration={5}
                                    start={item.start}
                                    end={item.end}
                                    suffix={item.suffix}
                                    prefix={item.prefix}
                                />
                            </div>
                            <p className="mt-2 mb-0 fw-semibold">{item.title}</p>
                            <p>{item.subtitle}</p>
                        </Col>
                    ))}
                </Row>
            </Container>
        </section>
    );
};

export default OurVision;
